apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask_hello
  template:
    metadata:
      labels:
        app: flask_hello
    spec:
      containers:
      - name: flask_hello
        image: 192.168.49.2:31155/flask_hello:latest
        ports:
        - containerPort: 5000
