apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: docker-registry
spec:
  type: NodePort
  selector:
    app: flask_hello
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31155
